Cldspt 9295 wmic performance
mitre/microsoft-windows-server-2016-stig-baseline pull request #55
Opened 2021-07-02 21:26 UTC by gregbeck-cms

2021-07-06 21:05 UTC, gregbeck-cms commented
There is a simpler built-in way to get the domain SID that does not require enabling the ActiveDirectory-Powershell feature, I'll make the change, test, and push to this branch.

2021-07-08 14:29 UTC, ejaronne commented
@burnsjared0415 , could the technique used at https://github.com/mitre/microsoft-windows-server-2019-stig-baseline/blob/69ebfebfa409ff35f35e90b30a4b1bbc8b956180/controls/V-93009.rb#L103-L114 be used effectively on this 2016 baseline?

2021-07-13 15:25 UTC, gregbeck-cms commented
Hi @ejaronne and @aaronlippold , this code works, but I am confused about why I need so many 'end's at the, well, end of the files. It seems like there are too many in each file, I couldn't get the indentation to work out nicely, may be a non-issue.

2021-07-15 16:31 UTC, ejaronne requested changes
I'm concerned about maintaining the purity of the original intent/content from the STIG author, especially **check and fix text**. Any deviation (however well meaning) from what a user sees in the original STIG guidance could cause confusion distrust as to the scope of the checks. Recommend instead, for example wrt V-73759.rb:
Leave the original fix text as is, then append:
"[The following text is not part of the original STIG, but added as helpful context from the InSpec profile test code developer (@gregbeck-cms)]:"
and add your statements, such as:
"  Domain Systems Only:
  - Enterprise Admins group (SID* S-1-5-21-root domain-519)
  - Domain Admins group (SID* S-1-5-21-domain-512)
  - Local account (SID* S-1-2-0) and member of Administrators group (SID S-1-5-32-544) or Local account
  (see Note below)
  All Systems:
  - Guests group (SID* S-1-5-32-546)
  * See SIDs in https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/security-identifiers-in-windows"

2021-07-15 16:41 UTC, gregbeck-cms commented
I have removed the deviations from the STIG text.

2021-07-22 13:17 UTC, ejaronne approved these changes

2021-07-22 13:48 UTC, karikarshivani commented on controls/V-73763.rb
> +  - Guests group
Missing the end double-quotes - which seems to be leading to the following code to be treated as a string

2021-07-22 13:48 UTC, karikarshivani commented on controls/V-73767.rb
> +  - Domain Admins group
Missing the end double-quotes

2021-07-22 13:49 UTC, karikarshivani commented on controls/V-73771.rb
> +  - Guests group
Missing the end double-quotes

2021-07-22 22:58 UTC, karikarshivani commented on controls/V-73759.rb
>          end
Updated this control to reflect the proposal for approval

2021-07-22 22:59 UTC, karikarshivani commented on controls/V-73759.rb
> +  #     skip 'This system is dedicated to the management of Active Directory, therefore this system is exempt from this control'
Check commented out until further research

2021-07-22 23:01 UTC, karikarshivani commented on controls/V-73759.rb
> +            its('SeDenyNetworkLogonRight') { should include "S-1-5-114" }
Added the SIDs for local accounts as per the updated STIG guidance. Test pending.

2021-07-27 17:30 UTC, karikarshivani commented
[MemberServer-Fail.json.txt](https://github.com/mitre/microsoft-windows-server-2016-stig-baseline/files/6887542/MemberServer-Fail.json.txt)
[MemberServer-Pass.json.txt](https://github.com/mitre/microsoft-windows-server-2016-stig-baseline/files/6887543/MemberServer-Pass.json.txt)
[Standalone-Fail.json.txt](https://github.com/mitre/microsoft-windows-server-2016-stig-baseline/files/6887544/Standalone-Fail.json.txt)
[Standalone-Pass.json.txt](https://github.com/mitre/microsoft-windows-server-2016-stig-baseline/files/6887545/Standalone-Pass.json.txt)

2021-07-27 17:30 UTC, karikarshivani commented on controls/V-73759.rb
> +            its('SeDenyNetworkLogonRight') { should include "S-1-5-114" }
Tested after adding Local accounts where needed

2021-07-27 17:30 UTC, karikarshivani commented on controls/V-73759.rb
> +  #     skip 'This system is dedicated to the management of Active Directory, therefore this system is exempt from this control'
Checked and included code where needed

2021-07-27 18:06 UTC, karikarshivani approved these changes

2021-07-28 17:13 UTC, merged